// Hopscope cross-language event contract — the SINGLE SOURCE OF TRUTH shared by the
// C# engine (gRPC server) and the Go eBPF agent (gRPC client, Phase 5).
//
// Rules:
//   * Additive-first. NEVER reuse a field number — it is the wire identity.
//   * Change this file FIRST, then regenerate BOTH sides in the same change.
//   * Keep congruent with Hopscope.Domain/Events/EventEnvelope.cs.
//   * Nullability mapping (proto3 has no null):
//       - parent_hop_id: empty string == null
//       - error_details: unset message == null
//   * payload_metadata is headers / routing keys / type-names ONLY — never message bodies.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: event.proto

package contractsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ingestion_Stream_FullMethodName = "/hopscope.v1.Ingestion/Stream"
)

// IngestionClient is the client API for Ingestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent → Engine. Client-streaming for back-pressure-friendly high throughput.
type IngestionClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventEnvelope, IngestAck], error)
}

type ingestionClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionClient(cc grpc.ClientConnInterface) IngestionClient {
	return &ingestionClient{cc}
}

func (c *ingestionClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventEnvelope, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ingestion_ServiceDesc.Streams[0], Ingestion_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventEnvelope, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingestion_StreamClient = grpc.ClientStreamingClient[EventEnvelope, IngestAck]

// IngestionServer is the server API for Ingestion service.
// All implementations must embed UnimplementedIngestionServer
// for forward compatibility.
//
// Agent → Engine. Client-streaming for back-pressure-friendly high throughput.
type IngestionServer interface {
	Stream(grpc.ClientStreamingServer[EventEnvelope, IngestAck]) error
	mustEmbedUnimplementedIngestionServer()
}

// UnimplementedIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionServer struct{}

func (UnimplementedIngestionServer) Stream(grpc.ClientStreamingServer[EventEnvelope, IngestAck]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedIngestionServer) mustEmbedUnimplementedIngestionServer() {}
func (UnimplementedIngestionServer) testEmbeddedByValue()                   {}

// UnsafeIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionServer will
// result in compilation errors.
type UnsafeIngestionServer interface {
	mustEmbedUnimplementedIngestionServer()
}

func RegisterIngestionServer(s grpc.ServiceRegistrar, srv IngestionServer) {
	// If the following call pancis, it indicates UnimplementedIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ingestion_ServiceDesc, srv)
}

func _Ingestion_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestionServer).Stream(&grpc.GenericServerStream[EventEnvelope, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ingestion_StreamServer = grpc.ClientStreamingServer[EventEnvelope, IngestAck]

// Ingestion_ServiceDesc is the grpc.ServiceDesc for Ingestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hopscope.v1.Ingestion",
	HandlerType: (*IngestionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Ingestion_Stream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "event.proto",
}
