// Hopscope cross-language event contract — the SINGLE SOURCE OF TRUTH shared by the
// C# engine (gRPC server) and the Go eBPF agent (gRPC client, Phase 5).
//
// Rules:
//   * Additive-first. NEVER reuse a field number — it is the wire identity.
//   * Change this file FIRST, then regenerate BOTH sides in the same change.
//   * Keep congruent with Hopscope.Domain/Events/EventEnvelope.cs.
//   * Nullability mapping (proto3 has no null):
//       - parent_hop_id: empty string == null
//       - error_details: unset message == null
//   * payload_metadata is headers / routing keys / type-names ONLY — never message bodies.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: event.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Per-hop lifecycle outcome. Ordinals MUST match Hopscope.Domain.Events.ExecutionStatus.
type ExecutionStatus int32

const (
	ExecutionStatus_SUCCESS       ExecutionStatus = 0
	ExecutionStatus_RETRYING      ExecutionStatus = 1
	ExecutionStatus_DEAD_LETTERED ExecutionStatus = 2
	ExecutionStatus_FAILED        ExecutionStatus = 3
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "RETRYING",
		2: "DEAD_LETTERED",
		3: "FAILED",
	}
	ExecutionStatus_value = map[string]int32{
		"SUCCESS":       0,
		"RETRYING":      1,
		"DEAD_LETTERED": 2,
		"FAILED":        3,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

// Failure detail. Present iff the hop failed/dead-lettered. truncated_stack_trace is
// bounded metadata, never a message body.
type ErrorDetails struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExceptionType       string                 `protobuf:"bytes,1,opt,name=exception_type,json=exceptionType,proto3" json:"exception_type,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TruncatedStackTrace string                 `protobuf:"bytes,3,opt,name=truncated_stack_trace,json=truncatedStackTrace,proto3" json:"truncated_stack_trace,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetails) GetExceptionType() string {
	if x != nil {
		return x.ExceptionType
	}
	return ""
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetTruncatedStackTrace() string {
	if x != nil {
		return x.TruncatedStackTrace
	}
	return ""
}

// The normalized envelope EVERY ingestor (in-proc provider OR remote agent) emits.
type EventEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                                                                                   // global correlation id
	HopId           string                 `protobuf:"bytes,2,opt,name=hop_id,json=hopId,proto3" json:"hop_id,omitempty"`                                                                                                         // unique per message instance (dedupe key)
	ParentHopId     string                 `protobuf:"bytes,3,opt,name=parent_hop_id,json=parentHopId,proto3" json:"parent_hop_id,omitempty"`                                                                                     // upstream hop that caused this; empty == null
	Source          string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                                                                                                    // originating component
	Destination     string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`                                                                                                          // exchange / topic / queue
	BrokerType      string                 `protobuf:"bytes,6,opt,name=broker_type,json=brokerType,proto3" json:"broker_type,omitempty"`                                                                                          // "RabbitMQ" | "Kafka" | "Redis" | ...
	PayloadMetadata map[string]string      `protobuf:"bytes,7,rep,name=payload_metadata,json=payloadMetadata,proto3" json:"payload_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // headers / routing keys / type-names ONLY
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                              // UTC at interception
	ExecutionStatus ExecutionStatus        `protobuf:"varint,9,opt,name=execution_status,json=executionStatus,proto3,enum=hopscope.v1.ExecutionStatus" json:"execution_status,omitempty"`
	ErrorDetails    *ErrorDetails          `protobuf:"bytes,10,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"` // unset == null
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventEnvelope) GetHopId() string {
	if x != nil {
		return x.HopId
	}
	return ""
}

func (x *EventEnvelope) GetParentHopId() string {
	if x != nil {
		return x.ParentHopId
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *EventEnvelope) GetBrokerType() string {
	if x != nil {
		return x.BrokerType
	}
	return ""
}

func (x *EventEnvelope) GetPayloadMetadata() map[string]string {
	if x != nil {
		return x.PayloadMetadata
	}
	return nil
}

func (x *EventEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventEnvelope) GetExecutionStatus() ExecutionStatus {
	if x != nil {
		return x.ExecutionStatus
	}
	return ExecutionStatus_SUCCESS
}

func (x *EventEnvelope) GetErrorDetails() *ErrorDetails {
	if x != nil {
		return x.ErrorDetails
	}
	return nil
}

type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Deduped       uint64                 `protobuf:"varint,2,opt,name=deduped,proto3" json:"deduped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *IngestAck) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestAck) GetDeduped() uint64 {
	if x != nil {
		return x.Deduped
	}
	return 0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\vhopscope.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\fErrorDetails\x12%\n" +
	"\x0eexception_type\x18\x01 \x01(\tR\rexceptionType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x15truncated_stack_trace\x18\x03 \x01(\tR\x13truncatedStackTrace\"\xa3\x04\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x15\n" +
	"\x06hop_id\x18\x02 \x01(\tR\x05hopId\x12\"\n" +
	"\rparent_hop_id\x18\x03 \x01(\tR\vparentHopId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\x12\x1f\n" +
	"\vbroker_type\x18\x06 \x01(\tR\n" +
	"brokerType\x12Z\n" +
	"\x10payload_metadata\x18\a \x03(\v2/.hopscope.v1.EventEnvelope.PayloadMetadataEntryR\x0fpayloadMetadata\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\x10execution_status\x18\t \x01(\x0e2\x1c.hopscope.v1.ExecutionStatusR\x0fexecutionStatus\x12>\n" +
	"\rerror_details\x18\n" +
	" \x01(\v2\x19.hopscope.v1.ErrorDetailsR\ferrorDetails\x1aB\n" +
	"\x14PayloadMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\tIngestAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\x12\x18\n" +
	"\adeduped\x18\x02 \x01(\x04R\adeduped*K\n" +
	"\x0fExecutionStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\f\n" +
	"\bRETRYING\x10\x01\x12\x11\n" +
	"\rDEAD_LETTERED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032K\n" +
	"\tIngestion\x12>\n" +
	"\x06Stream\x12\x1a.hopscope.v1.EventEnvelope\x1a\x16.hopscope.v1.IngestAck(\x01BUZ;github.com/hopscope/agent/internal/contracts/v1;contractsv1\xaa\x02\x15Hopscope.Contracts.V1b\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_proto_goTypes = []any{
	(ExecutionStatus)(0),          // 0: hopscope.v1.ExecutionStatus
	(*ErrorDetails)(nil),          // 1: hopscope.v1.ErrorDetails
	(*EventEnvelope)(nil),         // 2: hopscope.v1.EventEnvelope
	(*IngestAck)(nil),             // 3: hopscope.v1.IngestAck
	nil,                           // 4: hopscope.v1.EventEnvelope.PayloadMetadataEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	4, // 0: hopscope.v1.EventEnvelope.payload_metadata:type_name -> hopscope.v1.EventEnvelope.PayloadMetadataEntry
	5, // 1: hopscope.v1.EventEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: hopscope.v1.EventEnvelope.execution_status:type_name -> hopscope.v1.ExecutionStatus
	1, // 3: hopscope.v1.EventEnvelope.error_details:type_name -> hopscope.v1.ErrorDetails
	2, // 4: hopscope.v1.Ingestion.Stream:input_type -> hopscope.v1.EventEnvelope
	3, // 5: hopscope.v1.Ingestion.Stream:output_type -> hopscope.v1.IngestAck
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
